### ISSUE TITLE
Contact Us Form

### ISSUE THREAD

**Issue by MelissaMc20** [Code-Operative/Reuse#17]
[x] Styling has no padding? 
Square box to be removed and styling to match other areas.

[x] Tick box changed to match GDPR Compliance in sharing details with customer service

**Comment by nfys** [comment]
Contact us page styled.
GDPR tick box label changed... 
... will need a privacy page to link to

**Comment by MelissaMc20** [comment]
GDPR Tickbox seems to still be in lorem ipsum for me - I've added a task for Ken to create a privacy page.

**Comment by nfys** [comment]
Sorry, GDPR Tickbox done now on live also.

**Comment by MelissaMc20** [comment]
Perfect thanks Kate!
