### ISSUE TITLE
Manufacturer Disable

### ISSUE THREAD

**Issue by MelissaMc20** [Code-Operative/Reuse#19]
Disable being able to add a manfacturer in the product upload list.

Do not display manufacturer on the product page.

**Comment by MelissaMc20** [comment]
Can you hide the field on the product upload?

**Comment by kyeap** [comment]
is it not hidden for you? 

![image](https://user-images.githubusercontent.com/39419492/116139248-b9c2f400-a6cd-11eb-8967-bec6d4f44a78.png)

**Comment by MelissaMc20** [comment]
![image](https://user-images.githubusercontent.com/59023121/116260917-0b6f8b00-a76f-11eb-9f60-1421ed47f292.png)
Still there for me

**Comment by kyeap** [comment]
on https://reusenetwork.code-operative.co.uk/ and cache cleared?

**Comment by kyeap** [comment]
custom.js 

origninal file: 
/modules/kbmarketplace/views/templates/front/product/informations.tpl

override: 
/themes/child_interior_th/modules/kbmarketplace/views/templates/front/product/informations.tpl
