### ISSUE TITLE
Seller Profile Page

### ISSUE THREAD

**Issue by MelissaMc20** [Code-Operative/Reuse#20]
- [x] Privacy etc to be reorganised to sit at the bottom of the page 

- [x] Request to access data button hidden 

- [x] Tab to say 'sellers' instead of 'authorised sellers'

**Comment by kyeap** [comment]
Button
- disabled GRPR request for seller 

Seller page rearrangement 
- modules/kbmarketplace/views/templates/front/seller/seller_view_to_customer.tpl

Override file
- /themes/child_interior_th/modules/kbmarketplace/views/templates/front/seller/seller_view_to_customer.tpl
