### ISSUE TITLE
Seller Profile Information

### ISSUE THREAD

**Issue by MelissaMc20** [Code-Operative/Reuse#21]
[ ] Not display as tabs, display with next button to move through tabs, so all information has to be filled in before being able to complete.

**Comment by kyeap** [comment]
custom.js to change tab 

moved save button for all tabs to last tab, add next button to other tabs 

original: 
modules/kbmarketplace/views/templates/front/seller/profile_form.tpl

override: 
themes/child_interior_th/modules/kbmarketplace/views/templates/front/seller/profile_form.tpl
