### ISSUE TITLE
Apply Sale

### ISSUE THREAD

**Issue by MelissaMc20** [Code-Operative/Reuse#26]
[ ] Date Picker and Time Picker to be added instead of field that doesn't explain how to type it properly

**Comment by MelissaMc20** [comment]
Go Discounts and Offers > Catalog and coupon Details > fill in the first section > press 'Add new Deal' > Takes you to another page. 

![image](https://user-images.githubusercontent.com/59023121/116262310-53db7880-a770-11eb-915a-3b77e8613360.png)
 this image here, doesn't have a date picker and you have to do the date and time again? 

Can it either, populate from the previous page or have another date and time picker please. 

I typed '27-04-2021' + '30-04-21' into the boxes as they were blank and hit save and it changed them to what it displays in the picture and auto defaults to 1989...

**Comment by kyeap** [comment]
Sorry, you don't choose the first date (in the screenshot I sent you) that's the filter, you go directly to add new deal (which is also what's written in the docs) and then there you fill in the dateTIME (note: here a date is not enough as the deal manager takes both the date AND TIME) as it's more precise. So if you enter the date time in this format "2021-04-10 00:00:00" then will work. It has worked for me: 

![image](https://user-images.githubusercontent.com/39419492/116611322-276d5b00-a92e-11eb-8aa0-69b57a9a4343.png)

I have added the dateime format information into the documentations.

**Comment by MelissaMc20** [comment]
Could a prompt in the text field be added?
 "2021-04-10 00:00:00" 
This to sit inside the field?
