### ISSUE TITLE
Sign in button changed

### ISSUE THREAD

**Issue by MelissaMc20** [Code-Operative/Reuse#33]
[x] SIGN IN removed

[x] Button changed

[x] Double person display not needed

[x] Sign out text removed

[x] Hover image added

**Comment by nfys** [comment]
Sign in label is removed, icon updated.
Wondering if we need a hover style? Orange not accessible, but maybe the purple?
<img width="338" alt="Screenshot 2021-05-05 at 17 29 46" src="https://user-images.githubusercontent.com/1536728/117176220-8d8f2d80-adc7-11eb-9843-1b58133edc7e.png">

**Comment by MelissaMc20** [comment]
![image](https://user-images.githubusercontent.com/59023121/117293657-95071300-ae69-11eb-845a-e03a1dbd80a8.png)
My signed in version looks like this? 

Will make a version of the person that works like the heart hover

**Comment by nfys** [comment]
Oops! That's sorted now...

**Comment by MelissaMc20** [comment]
https://xd.adobe.com/view/b8a75ee8-e3ae-4cd4-ae39-51cd63a4d899-edf4/

Sign in Button and hover linked here and marked for export

**Comment by MelissaMc20** [comment]
![image](https://user-images.githubusercontent.com/59023121/117330216-5b480380-ae8d-11eb-8c3b-0276c90a7d68.png)
Could sign out be removed? 

Also, when not logged in, the profile icon doesn't exist. 
![image](https://user-images.githubusercontent.com/59023121/117330275-6bf87980-ae8d-11eb-9d43-87467d0379b6.png)

**Comment by nfys** [comment]
Removed 'Sign out' link
Included your hover profile icon - looks good :-)
