### ISSUE TITLE
Privacy Page

### ISSUE THREAD

**Issue by MelissaMc20** [Code-Operative/Reuse#35]
[ ] Blank Privacy Policy Page to be added (same as delivery etc)

**Comment by kyeap** [comment]
![image](https://user-images.githubusercontent.com/39419492/116750648-afb93200-a9fa-11eb-9fc6-3315e5846d53.png)

![image](https://user-images.githubusercontent.com/39419492/116750691-bd6eb780-a9fa-11eb-95c8-9b5e2806a7b6.png)
