### ISSUE TITLE
Search Result Page Styling

### ISSUE THREAD

**Issue by MelissaMc20** [Code-Operative/Reuse#37]

**Comment by nfys** [comment]
I've done the obvious changes... could you let me know if anything jumps out that needs attention?

**Comment by nfys** [comment]
> Relevance box styling original (needs rounded corners etc)

This is done, but I've left the height as lining everything else up will be tricky

> Refine your search on left side, subcategories 

This will be time consuming and difficult to do in the time scale

> Filter checkbox

These are styled now

**Comment by MelissaMc20** [comment]
Amazing, thanks Kate. Closing this issue.
