### ISSUE TITLE
Item Page Styling

### ISSUE THREAD

**Issue by MelissaMc20** [Code-Operative/Reuse#38]

**Comment by nfys** [comment]
This is done now hopefully!

**Comment by MelissaMc20** [comment]
Great, has it been pushed to the live site?

**Comment by nfys** [comment]
Yes I've updated custom.css on both dev and live.

**Comment by MelissaMc20** [comment]
Noticeable changes: (Just gonna write some notes and if you could let me know if they're not done because they're not possible within the template that would be great - if it's that they're time consuming and we don't have that time, let me know - TGOS were provided with wireframes for these pages) 

- Add Basket Button width Incorrect 
- Add to Wishlist Heart Icon still the original template Icon
- 'New' dispaying over product image is original template icon 
- Page layout incorrect?

**Comment by nfys** [comment]
>  Add Basket Button width Incorrect
The short answer is that the template doesn't allow it. The touchspin (quantity) form group is in the same container as the Add to cart button. The label 'Quantity' is outside this. To start you'd need to calculate the full width of section then minus the width of the label. Then you'd have to do the same for the form group and button elements. This would need to be adjusted for varying screen widths, and also browser differences in rendering type etc. So it's possible, but not practical given the project constraints.

> Add to Wishlist Heart Icon still the original template Icon
This is now updated on the product page

> ’New' displaying over product image is original template icon
I’ve tweaked the styling… circle display, colour… does this work better?

> Page layout incorrect?
While I’ve styled elements where possible using the figma, It’s not practical to change the page layout and the order that elements appear on the page using CSS only. I assume the product item template chosen was the best fit for the project requirements in that it contains the required interactive and content elements?

**Comment by MelissaMc20** [comment]
> The short answer is that the template doesn't allow it.
No worries! 

> This is now updated on the product page
Fab thank you! 

> I’ve tweaked the styling… circle display, colour… does this work better?
I think it needs to be the yellow star icon that's displayed on the 'new' section on the home page

>While I’ve styled elements where possible using the figma, It’s not practical to change the page layout and the order that elements....
That's great, just checking incase TGOS come back to us

**Comment by nfys** [comment]
> I think it needs to be the yellow star icon that's displayed on the 'new' section on the home page

Ah OK... I think there's also 'on sale' and best... I've saved out those icons and applied them to the 'on sale' and 'new' flags. Could you see how they look. Maybe add the flags to a few products to see if it works? I'm not seeing where to do that. Also is there a 'Best' flag?
