### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by MelissaMc20** [Code-Operative/Reuse#4]

**Comment by nfys** [comment]
This is now done... hopefully! Banner photos/text are also in from the figma.

**Comment by MelissaMc20** [comment]
Hero images aren't long enough to fit my screen, is this an us issue or a TGOS issue? 
- 
![image](https://user-images.githubusercontent.com/59023121/117331500-b75f5780-ae8e-11eb-8163-1ef9a73bf870.png)

Carousel arrows incorrect? 
- they use the back to top version, not the left and right version. Icon provided here: https://xd.adobe.com/view/b8a75ee8-e3ae-4cd4-ae39-51cd63a4d899-edf4/

![image](https://user-images.githubusercontent.com/59023121/117331818-073e1e80-ae8f-11eb-86b9-546be379dca4.png)
- Same as product page, 'new' symbol needs to be yellow star. Provided on the XD above ^ 
- Wishlist icon here original from template

**Comment by nfys** [comment]
>Hero images on wide screens
This is an 'us' issue. I've focused on ensuring the slides display well on smaller screens. It will be possible but time consuming to override these styles for full width image on wider screens. 
> carousel arrows
These are cleverly styled in the parent theme. And they look nice. It rather seems like reinventing the wheel to override these styles. Bearing in mind also the more styles we include in custom.css the greater the performance impact. If it's a deal breaker it can be done (probably!) :-)
> 'New' flag
This is done, might need some more flags adding to test display

**Comment by MelissaMc20** [comment]
Great, thanks Kate!
