### ISSUE TITLE
Mail Automation

### ISSUE THREAD

**Issue by kyeap** [Code-Operative/Reuse#43]
- [ ] Claire to give us/enter an email SMTP details

**Comment by kyeap** [comment]
Claire can set up the information herself if she can't give us the SMTP password. It's in the admin site under Advance Parameters -> Email (see screenshot below): 

![image](https://user-images.githubusercontent.com/39419492/116749587-12113300-a9f9-11eb-9ea3-74674b0dea8e.png)

**Comment by MelissaMc20** [comment]
She provided this email: info@reuse-home.org.uk

Is this the email I need to ask for the SMTP details for? or an alternate email address?

**Comment by kyeap** [comment]
the email that she wants to use for the store

**Comment by MelissaMc20** [comment]
Claire can't seem to get the SMTP changed 

I don't think we ever actually tested in. Tried putting our own server settings in and this is what I'm getting 

![image](https://user-images.githubusercontent.com/59023121/117476072-aed15480-af54-11eb-8bd6-dac81530f5de.png)

@King-Mob @kyeap Any thoughts?

**Comment by kyeap** [comment]
I have managed to connect prestashop with my gmail account and also sent an email over to contact@code-operative.co.uk. I think their email server is blocking prestashop from accessing it and claire would have to ask their email server system adminstrator to enable access from prestashop.
