### ISSUE TITLE
'New' Appears over drop down

### ISSUE THREAD

**Issue by MelissaMc20** [Code-Operative/Reuse#46]

**Comment by MelissaMc20** [comment]
Product page > move cursor towards nav bar > nav menu drops down > new stays over drop down 

![image](https://user-images.githubusercontent.com/59023121/117298033-cdf5b680-ae6e-11eb-821d-d459818064ad.png)

**Comment by nfys** [comment]
I can fix this with css I think...

**Comment by MelissaMc20** [comment]
Perfect, I'll assign it. 

Just noticed the quanties box does the same

**Comment by nfys** [comment]
Ah yes well spotted. I've changed the z-index on both those elements. Should be fixed now...
