### ISSUE TITLE
Post Code Check Styling

### ISSUE THREAD

**Issue by MelissaMc20** [Code-Operative/Reuse#48]
[ ] Design needs to match figma

See full issue

**Comment by MelissaMc20** [comment]
![image](https://user-images.githubusercontent.com/59023121/117434416-8df10b00-af24-11eb-88b1-ce849e863f26.png)

Currently when you check the postcode, this box appears. 

![image](https://user-images.githubusercontent.com/59023121/117434581-c1cc3080-af24-11eb-8af8-218ea71e2d4a.png)

Could it look like this?

**Comment by kyeap** [comment]
@MelissaMc20 I have roughly done it, can you let me know how you want to style it?

**Comment by MelissaMc20** [comment]
#0BA32C, 100% - Green Colour 
https://xd.adobe.com/view/b8a75ee8-e3ae-4cd4-ae39-51cd63a4d899-edf4/ - Tick can be found here and Cross can be found here
Drop text sizing to 1rem 
Yes delivery text to be: "This product can be delivered to your address." 
No delivery text to be: "This product is not available for delivery at that address. Collection available at -.- miles." (e.g 5.9) 
#F77B86, 100% - Red Colour

**Comment by kyeap** [comment]
Please check using the [test item](https://reuse-home.org.uk/chairs/38-test.html) i set up as some of the items there now are from a seller without a postcode set up.

**Comment by kyeap** [comment]
@MelissaMc20 added the cross and tick from figma

**Comment by MelissaMc20** [comment]
Looks great, thanks Ken
