### ISSUE TITLE
Search Page default list view - not tile view

### ISSUE THREAD

**Issue by MelissaMc20** [Code-Operative/Reuse#49]

**Comment by MelissaMc20** [comment]
![image](https://user-images.githubusercontent.com/59023121/117435712-0efcd200-af26-11eb-811e-727eb57506e4.png)

Default to this one please

**Comment by kyeap** [comment]
created a ticket for this

**Comment by King-Mob** [comment]
https://www.prestashop.com/forums/topic/323065-list-view-by-default/

Misread, thought this was about sellers page, not search. This should be helpful.

**Comment by kyeap** [comment]
overwritten the class from list to grid in `themes/child_interior_th/templates/catalog/listing/product-list.tpl`

`
    <section id="products" class="grid">
`

to 
`
  <section id="products" class="list">
`

in line 85

**Comment by kyeap** [comment]
changed the default active class so that the styling is correct at the first load:

an overwrite file is created in 
`themes/child_interior_th/templates/catalog/_partials/products-top.tpl`
`themes/child_interior_th/templates/catalog/_partials/products-bottom.tpl`
