### ISSUE TITLE
VAT Included hidden

### ISSUE THREAD

**Issue by MelissaMc20** [Code-Operative/Reuse#54]

**Comment by MelissaMc20** [comment]
![image](https://user-images.githubusercontent.com/59023121/117436462-e9bc9380-af26-11eb-92a3-9c8752ffc6af.png)

Don't display the VAT included text as not all items have this.

**Comment by kyeap** [comment]
This is done doing the following: 
BO -> Improve -> International -> Locations -> Countries -> select your country and push EDIT -> on the bottem "display tax label" -> No
