### ISSUE TITLE
Sign Up Form Styling

### ISSUE THREAD

**Issue by MelissaMc20** [Code-Operative/Reuse#57]

**Comment by MelissaMc20** [comment]
Not the footer sorry, the register as a seller page 

> https://reuse-home.org.uk/login?create_account=1&seller_registration_form=1

**Comment by nfys** [comment]
Ah... yes I see. I'll check if it can be done with custom.css

**Comment by nfys** [comment]
The 'Title' field only has Mr and Mrs. Can we add Miss and Ms? Or is it that only married ladies are allowed to be sellers :-)
...  or maybe it's easier if it's removed altogether?

**Comment by MelissaMc20** [comment]
@King-Mob Can you help with this? Is it possible to add 'Miss' and 'Ms' ?
I was thinking about a 'Prefer not to say' - but it's not a required field when filling the form
