### ISSUE TITLE
Font colour on hero banner white instead of blue on all except the map image

### ISSUE THREAD

**Issue by MelissaMc20** [Code-Operative/Reuse#58]

**Comment by nfys** [comment]
I can do this one. It's a class in the hero slide editor. I'll check and let you know for inclusion in the docs.

**Comment by nfys** [comment]
For dark backgrounds on the Hero Slider banners. Add custom class 'dark' within the banner editor
<img width="1077" alt="hero-slide-custom-class-for-dark-background" src="https://user-images.githubusercontent.com/1536728/118794228-49a12b80-b891-11eb-987c-f66241060d04.png">

**Comment by MelissaMc20** [comment]
Amazing, thanks Kate!
