### ISSUE TITLE
Map that displays seller information

### ISSUE THREAD

**Issue by King-Mob** [Code-Operative/Reuse#6]

**Comment by kyeap** [comment]
The following should return you the latitude and longitude of one store.

`
$db = \Db::getInstance();
//get id of all the sellers 
$sellerIdArraySQL = "select `id_seller` from `psrn_kb_mp_seller` ";
$sellerIDArr= $db->executeS($sellerIdArraySQL); 
$LonArr = array();
$LatArr = array();

//loop through each seller ID array and get seller id of each seller  
foreach ($sellerIDArr as $seller) {
                
$sql = "select `value` from `psrn_kb_mp_custom_field_seller_mapping` where `id_field` IN (23) AND `id_seller` = ".$seller['id_seller'];
    $resGoogleMapURL = $db->executeS($sql); 
    $googleMapURL = $resGoogleMapURL[0]['value'];
    $afterAT = strstr($googleMapURL,'@');
    $cut = strpos($afterAT,',');
    $slat = substr($afterAT, 1, $cut-1);
    $nolon = substr($afterAT, $cut + 1);
    $secondCommaPos = strpos($nolon,',');
    $slon = substr($nolon,0, $secondCommaPos);
    array_push($LonArr, $slon);
    array_push($LatArr, $slat);
}
            
return [$LonArr, $LatArr];
`
