### ISSUE TITLE
Blog Posts 'Previous' spelled incorrectly and 'standard' within admin side of module

### ISSUE THREAD

**Issue by MelissaMc20** [Code-Operative/Reuse#63]

**Comment by MelissaMc20** [comment]
![image](https://user-images.githubusercontent.com/59023121/121228276-750da980-c884-11eb-8f14-df1f1c67020d.png)

**Comment by MelissaMc20** [comment]
![image](https://user-images.githubusercontent.com/59023121/121229302-acc92100-c885-11eb-83a5-fdae5e2244be.png)

**Comment by King-Mob** [comment]
Fixed Previeus. Admin panel, I'll raise as a ticket for the Xpert blog maintainers
