### ISSUE TITLE
Database with data in development environment

### ISSUE THREAD

**Issue by javierginez** [Code-Operative/Reuse#72]
@kyeap we need a dump file of the database (structure and data for testing purposes) to use in docker local environment.

This is needed to create the queries

**Comment by kyeap** [comment]
We can use the existing development DB, there are some data in there, for that or what do you mean?

**Comment by javierginez** [comment]
> @javierginez We can use the existing development DB, there are some data in there, for that or what do you mean?

The teams asked for this DB to help them create queries and for testing purposes.

**Comment by javierginez** [comment]
Ok! We'll close this. We found the DB.
