### ISSUE TITLE
Enable both delivery and collection in advance search

### ISSUE THREAD

**Issue by javierginez** [Code-Operative/Reuse#76]
- [x] Check if we can tick "delivery" and "collection" in these search form. @renerecalde and @elalelopez 
- [ ] Estimate additional effort
- [ ] Design search results

**Comment by javierginez** [comment]
Hola @kyeap ! How are you?

Ale, René and Gus have checked today that is technically possible to execute a combination of queries/results when the user ticked "delivery" AND "collection" on the advance search form.

To do this, we'll need some additional effort not included in our initial estimation.

We are going to estimate this, and let you know later.

**Comment by javierginez** [comment]
![image](https://user-images.githubusercontent.com/86108968/126542110-b5e7505d-4ce3-4bb6-bf92-a78502af4c94.png)

**Comment by javierginez** [comment]
@kyeap could you start working on "Design search results" ?

**Comment by renerecalde** [comment]
This task was outside the scope of the project.
