### ISSUE TITLE
View for search bar

### ISSUE THREAD

**Issue by kyeap** [Code-Operative/Reuse#85]
- [x] look for the right hook 
- [x] HTML and CSS 
- [x] validation 
  - [x] postcode 
 - [x] disable distance field for delivery

**Comment by kyeap** [comment]
@elalelopez I have created the search bar by using the content box module and hooking it to top column, is that ok? Or do we need to create a .tpl file? Will we have a controller that takes form input?

**Comment by elalelopez** [comment]
> @elalelopez I have created the search bar by using the content box module and hooking it to top column, is that ok? Or do we need to create a .tpl file? Will we have a controller that takes form input?

Hi Ken, Do you know what files was modified?

Are you copied that files to the repository and das a merge with development1?

**Comment by kyeap** [comment]
> Hi Ken, Do you know what files was modified?

The modified files would be in module -> contentbox. This [module](https://contentbox.org/) lets you add custom html, css and js directly into a hook. 
 
> Are you copied that files to the repository and das a merge with development1?

No, I did it in the development server (before the the sync with development1) directly. I have the code stored in [codepen](https://codepen.io/kenjoo/pen/VwbMMgd) and will recreate it once I get the development server in the pipleline with development1 branch.

**Comment by kyeap** [comment]
just saw #73, not sure they are the same?

**Comment by elalelopez** [comment]
> just saw #73, not sure they are the same?

Hi @kyeap , yes, are the same (essentialy).

**Comment by elalelopez** [comment]
> > Hi Ken, Do you know what files was modified?
> 
> The modified files would be in module -> contentbox. This [module](https://contentbox.org/) lets you add custom html, css and js directly into a hook.
> 
> > Are you copied that files to the repository and das a merge with development1?
> 
> No, I did it in the development server (before the the sync with development1) directly. I have the code stored in [codepen](https://codepen.io/kenjoo/pen/VwbMMgd) and will recreate it once I get the development server in the pipleline with development1 branch.

I think will be possible integreate the search bar that you made with our module. We made a new module to manage all functionality about advance search.

So, i think there are two possiblitities:

1. Replicate your work directly inside our module.
2. Use your work and integreate with our module.

I need replicate you code in my local for integration test (option 2). Can you commit that changes into development1 branch or in a new separated branch? Or explain to me what steps i have to do for replicate your code in my local.

**Comment by kyeap** [comment]
> I need replicate you code in my local for integration test (option 2).  ...

I have tried to do that but have the following problems: 
- module not working on docker 
  - i have manage to upload the module (contentbox) on the docker but it doesn't work as it should [see picture below]( https://user-images.githubusercontent.com/39419492/127737018-f541a449-0077-4beb-bc0c-f83ca9de2713.png)
  - [this is how it should be](https://user-images.githubusercontent.com/39419492/127737064-982383c2-d873-4a4b-8cfe-2f960be12aec.png)

- git not tracking the module upload 
   - i see the file in the code after uploading the module over the backend
   - but i do not see the code in `git status` hence not able to commit 

![image](https://user-images.githubusercontent.com/39419492/127737018-f541a449-0077-4beb-bc0c-f83ca9de2713.png)

![image](https://user-images.githubusercontent.com/39419492/127737064-982383c2-d873-4a4b-8cfe-2f960be12aec.png)
