### ISSUE TITLE
Error while register as a seller

### ISSUE THREAD

**Issue by javierginez** [Code-Operative/Reuse#92]
Taken from Discord:

![image](https://user-images.githubusercontent.com/86108968/127927757-1a05b0a7-6faf-48d1-b30d-8e39b88212aa.png)

![image](https://user-images.githubusercontent.com/86108968/127927618-68c1aa74-213a-411e-8853-8928d74ca6a8.png)

![image](https://user-images.githubusercontent.com/86108968/127928402-5d080c07-8cc0-4240-8a29-fc4161f24952.png)

**Comment by javierginez** [comment]
Hi @kyeap !!
In order to be more efficient, we'll be working on this bug after having finished some tasks we have ongoing now.
Do you agree?

**Comment by kyeap** [comment]
Hi @javierginez, yes definitely. I just checked that it's a docker problem, the code works ok for this in the development server instance. So it's fine as I dont think we need to use this page for development.

**Comment by kyeap** [comment]
![image](https://user-images.githubusercontent.com/39419492/128412192-a9bafb79-c6df-42e4-8a93-4e2b1581af4e.png)

Got this when trying to approve seller. I think this is from the same bug?

**Comment by elalelopez** [comment]
The problem is the folder gb. Doesn't exist inside modules/kbmarketplace/mails/

That folder contains a templates email files. 

en folder doesn't exist too.

**Comment by renerecalde** [comment]
While not fixed, this task has been deprecated.
