### ISSUE TITLE
Error while adding module (Contentbox) in localhost

### ISSUE THREAD

**Issue by kyeap** [Code-Operative/Reuse#93]
Got the following [error](https://user-images.githubusercontent.com/39419492/128592756-e90940b0-5613-4117-a586-5d4027404250.png) after uploading a module in BO. 

![image](https://user-images.githubusercontent.com/39419492/128592756-e90940b0-5613-4117-a586-5d4027404250.png)

Further error description is mentioned [here](https://github.com/Code-Operative/Reuse/issues/85#issuecomment-890327223) in #85. This happens when the module is uploaded in the dev server and the code generated is copied into the localhost.

**Comment by kyeap** [comment]
Upon further investigation, it seems that the part unaccessible in the local dev environment (where the HTML content is inserted) is linked to the DB. The content Box create two tables in the DB "psrn_advancesearchbox_files" and "psrn_advancesearchbox". 

These data was stored when kate (frontend dev) edited the code in the dev server (using the module installed there) that is why when the same code works in dev server but not in localhost as the tables are empty in the localhost.

![image](https://user-images.githubusercontent.com/39419492/128593616-50f62cbc-f091-4929-9ed2-2372a3ffc1c8.png)

![image](https://user-images.githubusercontent.com/39419492/128593648-0e1fec86-fcba-46ba-abcf-c96006c34124.png)

**Comment by renerecalde** [comment]
While not fixed, this task has been deprecated.
