### ISSUE TITLE
Design for advance search results

### ISSUE THREAD

**Issue by kyeap** [Code-Operative/Reuse#97]
@kyeap could you start working on "Design search results" ?

_Originally posted by @javierginez in https://github.com/Code-Operative/Reuse/issues/76#issuecomment-890171486_

**Comment by kyeap** [comment]
- [x] place div in product list template
- [ ] styling 
- [ ] insert condition for display 
  - [ ] only when advance search is used

**Comment by renerecalde** [comment]
This task has been completed.
